backend:
  name: github
  repo: gojimms/gojimms
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

site_url: "https://gojimms.com"
display_url: "https://gojimms.com"

logo_url: "/assets/favicon/favicon.ico"

publish_mode: editorial_workflow

collections:

  # =========================
  # BLOG INDONESIA
  # =========================
  - name: "blog_id"
    label: "Blog Indonesia"
    folder: "content/posts/id"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Description", name: "description", widget: "text" }

      - { label: "Slug", name: "slug", widget: "string" }

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Tags"
        name: "tags"
        widget: "list"

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"

  # =========================
  # BLOG ENGLISH
  # =========================
  - name: "blog_en"
    label: "Blog English"
    folder: "content/posts/en"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Description", name: "description", widget: "text" }

      - { label: "Slug", name: "slug", widget: "string" }

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Tags"
        name: "tags"
        widget: "list"

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"